#!/bin/bash

set -e

compdir=$(cd "$(dirname $0)/.."; pwd)

# Clean
rm -f $compdir/*.s

# Compile to Jasmine
java -cp $compdir/mjc.jar:$compdir/lib/javacc.jar mjc.JVMMain $@ -S

# Compile to JVM bytecode
java -jar $compdir/lib/jasmin.jar $compdir/*.s > /dev/null

# Run it
java -cp $compdir "`basename -s.java $1`"
