#!/bin/bash

compdir=$(cd "$(dirname $0)/.."; pwd)
scratch=$(mktemp tmp.XXXXXXXXXX)

for program in `find $compdir/testcases/compile -name '*.java'`; do
    java -cp $compdir/bin mjc.JVMMain "$(cat $program)" > "$scratch"
    if [ $? -gt 0 ]; then
        echo "ERROR: False negative for \"$program\""
        cat "$scratch"
    fi
done

for program in `find $compdir/testcases/noncompile -name '*.java'`; do
    java -cp $compdir/bin mjc.JVMMain "$(cat $program)" > "$scratch"
    if [ $? -lt 1 ]; then
        echo "ERROR: False positive for \"$program\""
        cat "$scratch"
    fi
done

rm "$scratch"
