#!/bin/bash

compdir=$(cd "$(dirname $0)/.."; pwd)
scratch=$(mktemp tmp.XXXXXXXXXX)
java_classpath=$compdir/mjc.jar:$compdir/lib/javacc.jar

( cd $compdir; ant > /dev/null )

for program in `find $compdir/testcases/compile -name '*.java'`; do
    java -cp $java_classpath mjc.JVMMain "$program" -S > "$scratch"
    if [ $? -gt 0 ]; then
        echo "ERROR: False negative for \"$program\""
        cat "$scratch"
    fi
done

for program in `find $compdir/testcases/noncompile -name '*.java'`; do
    java -cp $java_classpath mjc.JVMMain "$program" -S > "$scratch"
    if [ $? -lt 1 ]; then
        echo "ERROR: False positive for \"$program\""
        cat "$scratch"
    fi
done

rm "$scratch"
