#!/bin/bash

set -e
set -o pipefail

compdir=$(cd "$(dirname $0)/.."; pwd)

(
    cd $compdir
    ant clean > /dev/null
)

if [ -f $compdir/build.xml ] && \
    [ -f $compdir/DESC ] && \
    [ -d $compdir/src ] && \
    [ -d $compdir/lib ] && \
    [ -f $compdir/report.pdf ]; then
    true
else
    echo "ERROR: Missing files in \"$compdir\"."
    exit 1
fi

if [ ! -s $compdir/report.pdf ]; then
    echo "NOTE: Empty report.pdf -- need to resubmit before oral presentation."
fi

if uuencode x </dev/null >/dev/null; then
    true
else
    echo "ERROR: The program \"uuencode\" is missing. Please install GNU package sharutils."
    exit 1
fi

(
    cd $compdir
    tar cf - * | gzip | uuencode x | mailx -s '' submit@tigris.csc.kth.se
)

exit 0
